
main:  collision_detection.c compute3LinkFreeWorkspace.c generate_polygons.c functions.c 
	gcc -o x.out collision_detection.c compute3LinkFreeWorkspace.c generate_polygons.c gnuplot_i.c functions.c -ljansson -lm 

clean: 
	rm main
	rm *.o
